### ISSUE TITLE
Error with Python 3.9

### ISSUE THREAD

**Issue by vsergeyev** [zapatacomputing/qe-qulacs#10]
It works well with Python 3.8, but with Python 3.9 it runs into error:

```
from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/fractions.py)
```

**Comment by max-radin** [comment]
Should be fixed now, see zapatacomputing/qe-qiskit#11.
